### PR TITLE
Adding post_status check.

### PR DESCRIPTION
**Pull request by jesgs**
Changing the SQL query to look for published ACF groups. Otherwise, the sql query pulls in all ACF groups, even ones in trash.

### CODE REVIEW

**Comment by MaximeCulea** [comment]
Hi @jesgs,
Thanx for your contribution !
I think that getting all `post_type`'s ACF fieldset is fine, that's the purpose of the "restoration".
Now, I have the feeling that a hook to filter that query will allow you to handle what you wanna do.

Do you want to repatch it or you wanna me to do it ?
Waiting for your response.

**Comment by jesgs** [comment]
@MaximeCulea thanks for responding! I can take care of it at some point, just need clarification on how you think it would work. Do you mean a custom filter on the results, or the sql query itself? Either would be easy to do and could look something like:
```php
$sql = "SELECT ID, post_title FROM $wpdb->posts WHERE post_title LIKE '%{$field_group['title']}%' AND post_type='".ACFPR_GROUP_POST_TYPE."'";

$matches = $wpdb->get_results(apply_filters('acf_recovery_filter_query', $sql));
```

Or:

```php
$matches = apply_filters('acf_recovery_filter_results', $wpdb->get_results("SELECT ID, post_title FROM $wpdb->posts WHERE post_title LIKE '%{$field_group['title']}%' AND post_type='".ACFPR_GROUP_POST_TYPE."'"));
```
Either option would work, but the former is quicker and wouldn't force someone to iterate over the results.

**Comment by MaximeCulea** [comment]
Better do :
```
$sql = "SELECT ID, post_title FROM $wpdb->posts WHERE post_title LIKE '%{$field_group['title']}%' AND post_type='".ACFPR_GROUP_POST_TYPE."'";

matches = $wpdb->get_results(apply_filters('acf_recovery_filter_query', $sql));
```
Thx @jesgs 👍

**Comment by MaximeCulea** [comment]
Hi @jesgs,
Will you patch it like previous comment ?
thx

**Comment by jesgs** [comment]
@MaximeCulea yup, I can! I've been pretty busy this week. Planned on looking things over tonight or this weekend.

**Comment by MaximeCulea** [comment]
Thx @jesgs,
Just changed the hook name, please use `acf_recovery\query\post_status` to only filter the post_status clause.
Cya

**Comment by jesgs** [comment]
@MaximeCulea Awesome!

**Pull request merged**
