### PR TITLE
FIX Deleted function acf_get_local()

### PR DESCRIPTION
**Pull request by steingeo**
Since the acf_get_local function has been deleted by ACF Pro this plugin is no longer working.
I didn't test this fix for many configurations but it worked for my projects. Hope this can help !

### CODE REVIEW

**Comment by MaximeCulea** [comment]
Hello @steingeo,

First of all, thank you for your PR :)

I have downloaded your PR zip to make some tests and I encountered some errors :

1. <pre>Warning: Invalid argument supplied for foreach() in ../acf-php-recovery.php on line 127</pre>
It is launched because no php's fields loaded.

2. After importing, I get <pre>Warning: Invalid argument supplied for foreach() in ../acf-php-recovery.php on line 19</pre>
Which maybe cause that the imported fields were empty.

Do you get the same ? If yes, would you mind correct it ?
Let me know.

**Comment by steingeo** [comment]
Hi @MaximeCulea,

Unfortunately I don't encounter this issue. My group_fields are all imported from my theme using the `acf_add_local_field_group()` function (which the ACF plugins provides). It worked well for me with ACF 5.7.12 and 5.7.13 and I'm using PHP 7.2.13.

Does your fields were well imported ? What the `acf_get_local_field_groups()` function is returning to you?

Could you give me more informations about your config for me to understand what could cause this issue in your side and try to correct it?

**Comment by MaximeCulea** [comment]
Strange, also using `acf_add_local_field_group()` in my theme but with ACF 5.7.9 and PHP 7.0.3.

My fields : [fields.txt](https://github.com/BeAPI/ACF-PHP-Recovery/files/2956218/fields.txt)

Sadly `acf_add_local_field_groups()` returns false :/ need to check why, because they are still displaying into the dashboard ^^

**Comment by SkoricIT** [comment]
I used the version of @steingeo and had zero problems. I already had defined Fields, though.

**Comment by smarterdigitalltd** [comment]
@steingeo thanks very much for this - working great with PHP 7.2.10 & ACF 5.7.13

**Comment by MaximeCulea** [comment]
👍

**Comment by andrewtmiller** [comment]
When I bulk imported my fields it did not import any of the Flexible Content nested fields for a few different field groups, but when I went back and re-imported them individually it seemed to work.

**Comment by acxiomdeveloper** [comment]
@steingeo @MaximeCulea - thanks for the fix. Working well on PHP 7.3.4 with WP 5.2

**Review by basjerome — APPROVED** [review]

**Comment by localhorst** [comment]
Can someone merge this pull request please? Thanks.

**Comment by MaximeCulea** [comment]
@localhorst To clarify, as I have been kicked out from the project, I can't anymore accept the PR.

**Comment by martinderm** [comment]
So, nobody is merging tis in? How funny, in the sense of childish *scnr*

**Comment by charles00willian** [comment]
Worked like a dream here! Thx

**Comment by peninah2** [comment]
Just used this pull request, thank you!

**Pull request merged**
